"""YOLO Waste Detector — Training Script.

Trains a YOLOv11n model to detect specific waste objects in images.
Detections are mapped to 4 app types: Plastic, Organic, E-Waste, Hazardous.

Expected dataset structure (YOLO format):
    data/
        images/
            train/      # training images
            val/        # validation images
        labels/
            train/      # YOLO-format label files (.txt)
            val/        # YOLO-format label files (.txt)
        data.yaml       # dataset config

    data.yaml example:
        train: ./data/images/train
        val: ./data/images/val
        nc: 11
        names:
          0: recyclable-waste-plastic
          1: recyclable-waste-nylonbag
          2: recyclable-waste-paper
          3: recyclable-waste-paperbag
          4: recyclable-waste-cardboard
          5: recyclable-waste-clothes
          6: recyclable-waste-shoe
          7: recyclable-waste-glass
          8: recyclable-waste-metal
          9: organic-waste
          10: hazardous-waste

Label format (.txt per image):
    <class_id> <x_center> <y_center> <width> <height>
    Values normalized to [0, 1].

Usage:
    python train_yolo.py --data data.yaml --epochs 50 --img_size 640
    python train_yolo.py --data data.yaml --epochs 100 --batch 16 --lr 0.01
"""
from __future__ import annotations

import argparse
import json
import shutil
import time
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────
OUTPUT_DIR = Path(__file__).parent / "models"
DEFAULT_DATA = Path(__file__).parent / "data" / "data.yaml"

# YOLO class names (must match data.yaml)
YOLO_CLASSES = [
    "recyclable-waste-plastic",
    "recyclable-waste-nylonbag",
    "recyclable-waste-paper",
    "recyclable-waste-paperbag",
    "recyclable-waste-cardboard",
    "recyclable-waste-clothes",
    "recyclable-waste-shoe",
    "recyclable-waste-glass",
    "recyclable-waste-metal",
    "organic-waste",
    "hazardous-waste",
]


def create_data_yaml(data_dir: Path, output_yaml: Path):
    """Auto-generate data.yaml from directory structure if not present."""
    images_train = data_dir / "images" / "train"
    images_val = data_dir / "images" / "val"

    if not images_train.exists():
        print(f"ERROR: Training images not found at {images_train}")
        return False

    nc = len(YOLO_CLASSES)
    names_str = "\n".join(f"  {i}: {name}" for i, name in enumerate(YOLO_CLASSES))

    yaml_content = f"""# SwachhLens Waste Detector — YOLO Dataset Config
# Auto-generated by train_yolo.py

train: {images_train.resolve()}
val: {images_val.resolve() if images_val.exists() else images_train.resolve()}

nc: {nc}
names:
{names_str}
"""
    output_yaml.parent.mkdir(parents=True, exist_ok=True)
    output_yaml.write_text(yaml_content)
    print(f"Created data.yaml at {output_yaml}")
    return True


def count_labels(data_dir: Path):
    """Count total labels and per-class distribution."""
    labels_dir = data_dir / "labels"
    if not labels_dir.exists():
        print(f"WARNING: Labels directory not found at {labels_dir}")
        return

    class_counts = {i: 0 for i in range(len(YOLO_CLASSES))}
    total_boxes = 0
    total_images = 0

    for label_file in labels_dir.rglob("*.txt"):
        total_images += 1
        for line in label_file.read_text().strip().split("\n"):
            if not line.strip():
                continue
            parts = line.split()
            if len(parts) >= 5:
                class_id = int(parts[0])
                if class_id in class_counts:
                    class_counts[class_id] += 1
                total_boxes += 1

    print(f"\nDataset statistics:")
    print(f"  Total images: {total_images}")
    print(f"  Total bounding boxes: {total_boxes}")
    print(f"  Per-class distribution:")
    for cid, name in enumerate(YOLO_CLASSES):
        count = class_counts.get(cid, 0)
        bar = "█" * min(count // 5, 40)
        print(f"    {cid:2d} {name:35s} {count:5d} {bar}")


def train(data_yaml: Path, args):
    """Train YOLOv11n using ultralytics."""
    from ultralytics import YOLO

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_model = OUTPUT_DIR / "waste_types_best.pt"

    # Load a pretrained YOLOv11n model (nano = fastest)
    model = YOLO("yolo11n.pt")

    print(f"\n{'='*60}")
    print(f"Training YOLOv11n on: {data_yaml}")
    print(f"  Epochs: {args.epochs}")
    print(f"  Image size: {args.img_size}")
    print(f"  Batch size: {args.batch}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Output: {output_model}")
    print(f"{'='*60}\n")

    t0 = time.time()

    results = model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.img_size,
        batch=args.batch,
        lr0=args.lr,
        patience=args.patience,
        device=args.device,
        workers=args.workers,
        project=str(OUTPUT_DIR),
        name="yolo_train",
        exist_ok=True,
        pretrained=True,
        optimizer="auto",
        verbose=True,
        seed=42,
    )

    elapsed = time.time() - t0
    print(f"\nTraining complete in {elapsed/60:.1f} minutes")

    # Find the best model
    best_path = OUTPUT_DIR / "yolo_train" / "weights" / "best.pt"
    if best_path.exists():
        shutil.copy2(best_path, output_model)
        print(f"Best model copied to: {output_model}")
    else:
        print(f"WARNING: Best model not found at {best_path}")

    # Save training metadata
    meta = {
        "model": "yolo11n",
        "epochs": args.epochs,
        "img_size": args.img_size,
        "batch": args.batch,
        "lr": args.lr,
        "classes": YOLO_CLASSES,
        "training_time_seconds": elapsed,
        "output": str(output_model),
    }
    meta_path = output_model.with_suffix(".meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    print(f"Metadata saved to: {meta_path}")

    return results


def main():
    parser = argparse.ArgumentParser(description="Train YOLO waste detector")
    parser.add_argument("--data", type=str, default=str(DEFAULT_DATA),
                        help="Path to data.yaml")
    parser.add_argument("--data_dir", type=str, default=None,
                        help="Data directory (auto-generates data.yaml if --data not found)")
    parser.add_argument("--epochs", type=int, default=50, help="Training epochs")
    parser.add_argument("--img_size", type=int, default=640, help="Image size")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    parser.add_argument("--lr", type=float, default=0.01, help="Initial learning rate")
    parser.add_argument("--patience", type=int, default=15, help="Early stopping patience")
    parser.add_argument("--device", type=str, default="", help="Device (cpu, 0, 0,1)")
    parser.add_argument("--workers", type=int, default=4, help="DataLoader workers")
    parser.add_argument("--stats_only", action="store_true",
                        help="Only show dataset statistics (no training)")
    args = parser.parse_args()

    data_yaml = Path(args.data)

    # Auto-generate data.yaml if needed
    if not data_yaml.exists() and args.data_dir:
        data_dir = Path(args.data_dir)
        if not create_data_yaml(data_dir, data_yaml):
            return
    elif not data_yaml.exists():
        print(f"ERROR: Data config not found: {data_yaml}")
        print(f"Provide --data path/to/data.yaml or --data_dir path/to/data/")
        return

    # Show stats
    data_dir = data_yaml.parent
    count_labels(data_dir)

    if args.stats_only:
        return

    # Train
    train(data_yaml, args)


if __name__ == "__main__":
    main()
